### ISSUE TITLE
Settings / Shuffle - buttons does not work

### ISSUE THREAD

**Issue by Hme89** [butterproject/butter-desktop#19] opened 2015-10-24 02:09 UTC
```
>> [29091:1024/035842:INFO:CONSOLE(21)] ""%c[%cERROR%c] TypeError: Cannot read property 'authenticated' of null" "color: black;" "color: red;" "color: black;" "TypeError: Cannot read property 'authenticated' of null\n    at eval (eval at \u003Canonymous\u003E (app://host/src/app/vendor/underscore/underscore.js:1454:20), \u003Canonymous\u003E:272:23)\n    at template (app://host/src/app/vendor/underscore/underscore.js:1461:21)\n    at Object.Marionette.Renderer.render (app://host/src/app/vendor/marionette/lib/backbone.marionette.js:1655:14)\n    at Marionette.ItemView.Marionette.View.extend._renderTemplate (app://host/src/app/vendor/marionette/lib/backbone.marionette.js:2117:38)\n    at Marionette.ItemView.Marionette.View.extend.render (app://host/src/app/vendor/marionette/lib/backbone.marionette.js:2085:12)\n    at Marionette.Region.Marionette.Object.extend._renderView (app://host/src/app/vendor/marionette/lib/backbone.marionette.js:1210:12)\n    at Marionette.Region.Marionette.Object.extend.show (app://host/src/app/vendor/marionette/lib/backbone.marionette.js:1138:14)\n    at Backbone.Marionette.LayoutView.extend.showSettings (app://host/src/app/lib/views/main_window.js:419:27)\n    at triggerEvents (app://host/src/app/vendor/backbone/backbone.js:368:57)\n    at triggerApi (app://host/src/app/vendor/backbone/backbone.js:356:19)"", source: app://host/src/app/app.js (21)
>> [29091:1024/035842:INFO:CONSOLE(272)] "Uncaught TypeError: Cannot read property 'authenticated' of null", source: app://host/src/app/index.html (272)
```

This message gets produced for each click on the _settings_ button.

Running on Manjaro Linux 64bit (arch).
Cloned master branch, installed / built / ran  according to _quickstart_ method.

I get a simmilar message when pressing the _shuffle_ button.

Let me know if you want some logs or for me to try something else, i'm not that technical, but
will help with what i can :)

**Comment by douglascamata** [comment] 2015-10-24 15:56
Someone's working on a fix at #25

**Comment by xaiki** [comment] 2015-10-24 19:08
merged #25 please confirm it fixed your issue.

**Comment by Hme89** [comment] 2015-10-24 22:10
```
>> [9812:1025/000750:INFO:CONSOLE(21)] ""%c[%cERROR%c] couldn't find provider" "color: black;" "color: red;" "color: black;" "Yts"", source: app://host/src/app/app.js (21)
>> [9812:1025/000750:INFO:CONSOLE(21)] ""%c[%cERROR%c] TypeError: Cannot read property 'random' of null" "color: black;" "color: red;" "color: black;" "TypeError: Cannot read property 'random' of null\n    at App.View.FilterBar.Backbone.Marionette.ItemView.extend.randomMovie (app://host/src/app/lib/views/browser/filter_bar.js:445:37)\n    at HTMLDivElement.jQuery.event.dispatch (app://host/src/app/vendor/jquery/dist/jquery.js:4435:9)\n    at HTMLDivElement.elemData.handle (app://host/src/app/vendor/jquery/dist/jquery.js:4121:28)"", source: app://host/src/app/app.js (21)
>> [9812:1025/000750:INFO:CONSOLE(445)] "Uncaught TypeError: Cannot read property 'random' of null", source: app://host/src/app/lib/views/browser/filter_bar.js (445)
```
_settings_ now works, _shuffle_ gives the error above, with spinning "loading"-circles endlessly....
Pushing any other buttons resumes normal operation

**Comment by MrAdder** [comment] 2015-10-25 11:50
Shuffle/Random at this time will not work as the API that we are using does not have this enabled I will work on getting this feature to work in a different way that it does currently.

**Comment by Hme89** [comment] 2015-10-25 12:51
Ok :)

Should I then close this issue or leave it open?

**Comment by MrAdder** [comment] 2015-10-25 12:52
Leave it open for now :) So its here for refrence

**Comment by Hme89** [comment] 2015-10-27 15:26
No longer gives endless loop, but displays _Error loading data, please try again later_
```
>> [6171:1027/162428:INFO:CONSOLE(16)] ""[%cWARNING%c] Vodo API endpoint '%s' failed." "color: orange;" "color: black;" "http://butter.vodo.net/popcorn"", source: app://host/src/app/app.js (16)
```

**Comment by MrAdder** [comment] 2015-10-27 15:42
This we are aware of and working on fixing

**Comment by xaiki** [comment] 2015-10-28 09:02
@MrAdder the vodo api can randomize, but it won't because it has ... 14 elements... but you have a local db you can just implement a random there.

**Comment by vankasteelj** [comment] 2016-12-03 11:39
@xaiki is it fixed?

**Comment by xaiki** [comment] 2016-12-03 15:15
should be...

**Comment by xaiki** [comment] 2016-12-03 15:15
confirmed fixed

**Closed by xaiki** 2016-12-03 15:15 UTC
Labels: bug
